-- broker_risk_list → broker_risk_list_migrated.
--
-- RENAMED, NOT DROPPED. Its 959 rows are the only copy of the original letter
-- flags, and this branch changes the board's entire flag source in one go. If
-- the mapping turns out wrong on prod, re-deriving from the original beats
-- reconstructing it from 997 rows that were generated by the thing under
-- suspicion.
--
-- Nothing references it any more: v_load_broker_risk was repointed at
-- v_broker_flags_current in the previous migration, and the load counts were
-- confirmed identical either side (identity 1,136, nonpayment 188,
-- unclassified 2) before this ran.
--
-- Drop it in a later branch, once the panel has been watched on prod.

alter table if exists public.broker_risk_list rename to broker_risk_list_migrated;
